name: hiretop_mobile_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^1.4.0
  path: ^1.9.0
  path_provider: ^2.1.2
  retrofit: ^4.1.0
  stacked: ^3.4.0
  stacked_services: ^1.4.0
  velocity_x: ^4.1.2

  stacked_shared: any
  flutter_staggered_grid_view: ^0.7.0
  faker: ^2.1.0
  intl: ^0.18.1
  timeago: ^3.6.1
  file_picker: ^6.1.1
  dotted_border: ^2.1.0
  flutter_xlider: ^3.5.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal

        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
          style: normal

        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal

        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal

        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic


flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
